# Generated by Django 5.0.6 on 2024-07-06 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='user',
            field=models.ManyToManyField(related_name='organisations', to=settings.AUTH_USER_MODEL),
        ),
    ]
